#+TITLE: The Big O Notation
A simplified analysis of an algorithm's efficiency.
It gives complexity in terms of (n) / input size

* Types of Measurement:
1. Worst Case
2. Best Case
3. Average Case

* Rules
1. Ignores constants
    #+BEGIN_EXAMPLE 
    5n ---> O(n) or if you have a function running times of 5n, it runs O(n)
    because it gets large the 5 doesn't matter as n grows 
    #+END_EXAMPLE

2. Certain terms dominate others.
    #+BEGIN_EXAMPLE 
    O(1) < O(logn) < O(n) < O(nlogn) < O(n^2) < O(2^n) < O(n!)
    #+END_EXAMPLE

* Constant Time 
#+BEGIN_EXAMPLE 
x = 5 + (15 * 20);
#+END_EXAMPLE
    Does not depend on input size, therefore it is O(1) or constant time 

#+BEGIN_EXAMPLE 
x = 5 + (15 * 20); 
y = 15 - 2
print x + y;
#+END_EXAMPLE

Add each of their times for the notation.

total time = O(1) + O(2) + O(3) which is 3 * O(1)

But, we drop constants so this is still O(1).

* Linear Time
#+BEGIN_EXAMPLE 
for x in range(0, n): // for loops nth times 
    print x; // O(1)
#+END_EXAMPLE
    total time = N * O(1) 
    
    This would be O(N).

#+BEGIN_EXAMPLE 
y = 5 + (15 * 20); // O(1)
for i in range (0, n): // O(N)
    print x;
#+END_EXAMPLE

    total time = O(1) + O(N)
    
    Drop the lowest term, O(1).
    
    This would be O(N) since for loop dominates run time.

* Quadratic Time
#+BEGIN_EXAMPLE 
for x in range (0, n): // O(N)
    for y in range(0, n): // O(N)
        print x*y;
#+END_EXAMPLE

    total time = N * N * O(1)
    
    Since there are to loops, it would be O(N^2)

* Examples
#+BEGIN_EXAMPLE 
x = 5 + (15 * 20); 
for x in range(0, n):
    print x;
for x in range (0, n):
    for y in range (0, n):
        print x * y;
#+END_EXAMPLE
    total time = O(1) * O(n) * O(n^2)
    
    total time = O(n^2) // Drop lowest terms 

#+BEGIN_EXAMPLE 
if x > 0:
    // O(1)
else if x < 0:
    // O(logn)
else:
    // O(n^2)
#+END_EXAMPLE
    Look at the loop with the largest run time/worst case.
    
    total time = O(n^2)
